"""Create a source-faithful evidence extract from the supplied Nilgiris DDMP.

This is intentionally an evidence-preservation tool, not a table digitiser.
In particular, it does not turn printed coordinates into numeric geometry, link
locations to project villages, or assign event dates or ML labels.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

from pypdf import PdfReader


ROOT = Path(__file__).resolve().parents[1]
PDF = ROOT / "data/raw/disaster/Nilgiris-DDMP.pdf"
SOURCES = ROOT / "data/sources"
PROCESSED = ROOT / "data/processed/disaster"

# PDF viewer page numbers (one-indexed).  The final group is deliberately
# limited to the detailed tables that correspond to Table 5.5's 283 total.
EVIDENCE_PAGES = {
    "rain_gauge_and_weather_station_tables": list(range(15, 18)),
    "historical_disaster_chronology": list(range(52, 83)),
    "august_2019_gsi_landslide_table_and_context": list(range(71, 78)),
    "vulnerable_location_abstract_and_detail_tables": list(range(102, 117)),
}


def page_text(reader: PdfReader, page_number: int) -> str:
    return reader.pages[page_number - 1].extract_text() or "[No extractable text]"


def main() -> None:
    if not PDF.is_file():
        raise FileNotFoundError(f"DDMP source PDF is required: {PDF}")

    SOURCES.mkdir(parents=True, exist_ok=True)
    PROCESSED.mkdir(parents=True, exist_ok=True)
    reader = PdfReader(PDF)
    digest = hashlib.sha256(PDF.read_bytes()).hexdigest()

    manifest = {
        "artifact_type": "DDMP source-faithful evidence manifest",
        "source_file": "data/raw/disaster/Nilgiris-DDMP.pdf",
        "source_sha256": digest,
        "pdf_page_count": len(reader.pages),
        "explicit_record_counts": {
            "proposed_automatic_rainguage_stations": 35,
            "automatic_weather_stations": 4,
            "gsi_august_2019_landslide_records": 77,
            "table_5_5_vulnerable_locations_total": 283,
        },
        "source_table_pages": {
            "table_2_6_proposed_automatic_rainguage_stations": [16, 17],
            "automatic_weather_stations_list": [17],
            "table_5_3_gsi_august_2019_landslides": [71, 72, 73, 74, 75],
            "table_5_5_vulnerable_location_abstract": [102],
            "detailed_vulnerable_hamlet_tables_for_table_5_5": list(range(103, 117)),
        },
        "structured_row_csv_created": False,
        "printed_total_integrity_note": (
            "Table 5.5 prints a grand total of 283. Its printed class totals "
            "(68 Very Highly Vulnerable, 89 Highly Vulnerable, 77 Medium "
            "Vulnerable, and 48 Low Vulnerable) sum to 282. This discrepancy "
            "is preserved and not reconciled."
        ),
        "why_no_new_row_csv": (
            "The DDMP's multi-page, visually laid-out GSI and vulnerable-hamlet "
            "tables have extraction line wraps and typography/OCR substitutions. "
            "A row/field CSV would require interpretation or normalisation and could "
            "silently alter source evidence. The accompanying page-faithful text extract "
            "is the reproducible record instead."
        ),
        "prohibitions_observed": [
            "No event-to-village linkage.",
            "No inferred dates, coordinates, CRS, or datum.",
            "No labels, negative samples, model training, or predictions.",
            "No modification of existing rainfall, terrain, event, boundary, or ML files.",
        ],
    }
    (PROCESSED / "ddmp_evidence_manifest.json").write_text(
        json.dumps(manifest, indent=2) + "\n", encoding="utf-8"
    )

    output = [
        "# Nilgiris DDMP source-faithful evidence extract",
        "",
        "Generated by `pipeline/extract_ddmp_evidence.py` from "
        "`data/raw/disaster/Nilgiris-DDMP.pdf`.",
        "",
        f"- Source SHA-256: `{digest}`",
        f"- PDF pages: {len(reader.pages)}",
        "- Explicit DDMP counts preserved: 35 proposed ARG stations; 4 AWS "
        "records; 77 GSI August-2019 landslide records; 283 Table 5.5 "
        "vulnerable locations.",
        "- Table 5.5's printed class totals add to 282 although it prints a grand "
        "total of 283; this source discrepancy is not reconciled.",
        "- This is source text, not a spatial dataset: coordinates remain exactly "
        "as extracted; no CRS/datum, location identity, event date, or linkage is inferred.",
        "- No row-level CSV is produced for the GSI or 283-location tables because "
        "their PDF layout cannot be safely normalised without interpretation.",
        "",
        "## Extracted source pages",
    ]
    for section, pages in EVIDENCE_PAGES.items():
        output.extend(["", f"## {section.replace('_', ' ').title()}"])
        for number in pages:
            output.extend(["", f"### PDF page {number}", "", "```text", page_text(reader, number), "```"])
    (SOURCES / "ddmp_pdf_evidence_extract.md").write_text(
        "\n".join(output) + "\n", encoding="utf-8"
    )


if __name__ == "__main__":
    main()
